apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bolt-deployment
  labels:
    app: slack-bolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-bolt
  template:
    metadata:
      labels:
        app: slack-bolt
    spec:
      imagePullSecrets:
        - name: jfrog-registry-secret   # <-- added here
      containers:
        - name: slack-bolt-container
          image: trialymloms.jfrog.io/bot-docker/slack-bolt-app:1.14
          ports:
            - containerPort: 3000
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-env
                  key: SLACK_BOT_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-env
                  key: SLACK_SIGNING_SECRET
